### ISSUE TITLE
User can set `Fragment` size inconsistently

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/dataformats#15]
The `Fragment` ctor takes a list of data payload pointers and (among other things) uses them to calculate the payload size and set it in the `FragmentHeader`. The user then has to call `set_fragment_header()` to set the various information in the header, which includes the size. Since `set_fragment_header()` just `memcpy`s the contents of its argument, the fragment header size gets overwritten with whatever the user set, which may be inconsistent with the actual size.

I'm not sure what the best solution is here. Given that `Fragment` can calculate the payload size, I favour just calculating it and not letting the user tell `Fragment` a potentially-wrong value, but we can't stop the user doing that while there's a member for size in `FragmentHeader`. Maybe throw if `set_fragment_header()` is given a header with the wrong value of size?

**Comment by eflumerf** [comment]
Another option would be for set_fragment_header to instead do a member-wise set of the header fields, leaving the size field alone as that is only set at Fragment construction...
