### ISSUE TITLE
Memory leak in TriggerRecord?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/dataformats#4]
I wonder if there is a memory leak in the TriggerRecord class.  The class manages the list of Fragments using bare pointers, and I haven't found any place where the memory associated with those pointers is freed.

As part of investigating this (and fixing it, if needed), I would like to request a unit test that checks for this memory leak, in the spirit of "test twice, fix once".  The unit test that I'm imagining would create and destroy a suitable number of TriggerRecord instances, including Fragments within them.  And, the unit test would check that the memory used by the current process does not grow significantly.

At the moment, my sense is that the only(?) way to check for memory growth is to examine the contents of the /proc/self/statm file.  (Other tools like getrusage don't seem to actually help.)  I can imagine a re-usable function that we add to our dunedaq toolkit that fetches the memory usage from the statm file.  I haven't made time to write that yet, but I can contribute to if, if that would be helpful.

**Comment by eflumerf** [comment]
I don't know if it would work on a unit test level, but Valgrind can be very good for detecting memory leaks as well.

**Comment by eflumerf** [comment]
I think the intention of the code as written is that the TriggerRecord would not be the owner of the Fragment pointers, which is why bare pointers were used instead of smart pointers. I think that this is something that can easily change to meet the needs of the DataFlow modules which are assembling TriggerRecords and writing them to files.

**Comment by bieryAtFnal** [comment]
Thinking about the ownership of the Fragments...  
What we've sketched out within the Dataflow Scope so far is that the Readout Scope will pass Fragments to the FragmentReceiver using Queue(s) that contain unique_ptrs to Fragments.  As such, the FragmentReceiver will hand over ownership of the Fragment memory blocks to the TriggerRecord.  
Other options are certainly possible, but it seems to me that other models might get complicated.  Assigning ownership to one of the DAQModules would mean that we'd need to add communication channels to that module to tell it when to allocate and free memory blocks.  Some sort of process-wide Fragment pool might be possible, but that should be discussed, if that is a proposal.  Is there a straightforward model that I'm not seeing?
This seems like a good topic for discussion at an upcoming MiniDAQApp meeting, and I will add it to the list.

As for whether the TriggerRecord class has a vector of bare pointers or smart pointers to Fragments, I don't have a strong opinion (although others might).  At a previous MiniDAQApp discussion, we agreed that we would *not* try to provide a TriggerRecord implementation that places the TRHeader and all of the Fragments in contiguous memory, at this point in time, but that may happen at some point in time, so we should keep it in mind.

**Comment by eflumerf** [comment]
As decided in group meeting, https://github.com/DUNE-DAQ/dataformats/pull/5 has been created to resolve this Issue.
