### ISSUE TITLE
Additional field in GeoID someday for readout/detector type?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/dataformats#48]
Will we need an additional field in GeoID at some point in time to distinguish between the readout of different electronics/detector types?

For example, I don't know if Photon System detectors will be grouped by APA in the horizontal drift Far Detector module, but if so, then it seems like we will need to distinguish between a request to read out the TPC data from APA5 from the Photon data from APA5.

If the Photon System detectors are grouped in a different way than APA, then the changes to GeoID may need to be even more radical.  

I'm just filing this Issue now to raise the issue and help us remember it, if that is useful.

**Comment by eflumerf** [comment]
Resolved by #62
