### ISSUE TITLE
PACMANFrame Updates

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/dataformats#76]
As stated in PR #74, it would probably be a good idea to revisit the code and add structs to define the data format instead of relying on byte and bit offsets and pointer arithmetic. This issue can also be used to capture any needed style updates (@jcfreeman2).

Additionally, it would probably be a good idea to implement a unit test suite for this class, as that will help document the supported data format and provide an in-package build target.

**Comment by alessandrothea** [comment]
Right, in fact more than a good idea having an overlay class is a requirement for `PACManFrame.hpp` be included in 2.8...
